-- ScratchBird migration mapping baseline for UserEntity
CREATE TABLE IF NOT EXISTS sys.users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(320) NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_users_email ON sys.users (email);
