package com.scratchbird.hibernate;

import java.util.Map;
import org.hibernate.dialect.PostgreSQLDialect;

/**
 * ScratchBird Hibernate dialect facade.
 *
 * Extends PostgreSQL semantics while exposing deterministic ScratchBird contract
 * helpers used by integration tests and adapter code.
 */
public class ScratchBirdDialect extends PostgreSQLDialect {

  public Map<String, String> getScratchBirdTypeContributions() {
    return ScratchBirdTypeMappings.defaultHibernateTypes();
  }

  public String mapScratchBirdTypeToHibernate(String scratchBirdType) {
    return ScratchBirdTypeMappings.mapToHibernateType(scratchBirdType);
  }

  public boolean supportsRecursiveSchemaMetadata() {
    return true;
  }

  public String formatQualifiedName(String schema, String objectName) {
    if (objectName == null || objectName.isBlank()) {
      throw new IllegalArgumentException("objectName is required");
    }
    if (schema == null || schema.isBlank()) {
      return quoteIdentifier(objectName);
    }
    return quoteIdentifier(schema) + "." + quoteIdentifier(objectName);
  }

  public String formatIdentityColumnClause(String columnName) {
    return quoteIdentifier(columnName) + " bigint generated by default as identity";
  }

  private String quoteIdentifier(String value) {
    return "\"" + value.replace("\"", "\"\"") + "\"";
  }
}
