apiVersion: v1
kind: Service
metadata:
  name: {{ include "scratchbird-sidecar.fullname" . }}-scratchbird
  labels:
    {{- include "scratchbird-sidecar.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: {{ include "scratchbird-sidecar.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: scratchbird
      port: {{ .Values.scratchbird.port }}
      targetPort: scratchbird
      protocol: {{ .Values.scratchbird.protocol }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "scratchbird-sidecar.fullname" . }}-sidecar
  labels:
    {{- include "scratchbird-sidecar.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: {{ include "scratchbird-sidecar.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: sidecar
      port: {{ .Values.sidecar.proxyPort }}
      targetPort: sidecar
      protocol: {{ .Values.scratchbird.protocol }}
