/*
 * ScratchBird-driver
 * Copyright (c) 2025-2026 Dalton Calford
 *
 * Licensed under the Initial Developer's Public License Version 1.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at:
 * https://www.firebirdsql.org/en/initial-developer-s-public-license-version-1-0/
 */
/*
 * ScratchBird JDBC Driver
 * Copyright (c) 2025 ScratchBird Project
 */
package com.scratchbird.jdbc;

import java.sql.*;
import java.util.*;
import java.util.concurrent.atomic.AtomicBoolean;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 * JDBC Statement implementation for ScratchBird.
 */
public class SBStatement implements Statement {

    private static final Logger LOGGER = Logger.getLogger(SBStatement.class.getName());

    // Parent connection
    protected final SBConnection connection;

    // ResultSet properties
    protected final int resultSetType;
    protected final int resultSetConcurrency;
    protected final int resultSetHoldability;

    // Statement state
    protected final AtomicBoolean closed = new AtomicBoolean(false);
    protected boolean poolable = false;
    protected boolean closeOnCompletion = false;
    protected int maxRows = 0;
    protected long largeMaxRows = 0;
    protected int maxFieldSize = 0;
    protected int queryTimeout = 0;
    protected int fetchDirection = ResultSet.FETCH_FORWARD;
    protected int fetchSize = 0;
    protected String cursorName;

    // Results
    protected SBResultSet currentResultSet;
    protected long updateCount = -1;
    protected boolean moreResults = false;
    protected List<String> batchStatements = new ArrayList<>();

    // Warnings
    protected SQLWarning warnings;

    // Generated keys
    protected SBResultSet generatedKeys;

    /**
     * Creates a new statement.
     */
    public SBStatement(SBConnection connection, int resultSetType,
                       int resultSetConcurrency, int resultSetHoldability) {
        this.connection = connection;
        this.resultSetType = resultSetType;
        this.resultSetConcurrency = resultSetConcurrency;
        this.resultSetHoldability = resultSetHoldability;
        this.fetchSize = connection.getConnectionProperties().getDefaultRowFetchSize();
    }

    @Override
    public ResultSet executeQuery(String sql) throws SQLException {
        checkClosed();
        clearResults();
        int pageSize = fetchSize > 0 ? fetchSize : 0;
        if (maxRows > 0 && pageSize > 0) {
            pageSize = Math.min(pageSize, maxRows);
        }

        if (pageSize > 0) {
            SBQueryResult result = connection.getProtocol().executeStreaming(sql, pageSize, queryTimeout * 1000);
            if (result.getStream() == null) {
                throw new SQLException("Query did not return a result set", "02000");
            }
            currentResultSet = new SBResultSet(this, result.getStream(), maxRows);
            return currentResultSet;
        }

        SBQueryResult result = connection.getProtocol().execute(sql, maxRows, queryTimeout * 1000);
        if (result.getColumns() == null || result.getColumns().isEmpty()) {
            throw new SQLException("Query did not return a result set", "02000");
        }
        currentResultSet = new SBResultSet(this, result.getColumns(), result.getRows());
        return currentResultSet;
    }

    @Override
    public int executeUpdate(String sql) throws SQLException {
        return (int) executeLargeUpdate(sql);
    }

    @Override
    public long executeLargeUpdate(String sql) throws SQLException {
        checkClosed();
        clearResults();

        SBQueryResult result = connection.getProtocol().execute(sql, maxRows, queryTimeout * 1000);

        if (result.getColumns() != null && !result.getColumns().isEmpty()) {
            throw new SQLException("executeUpdate cannot return a ResultSet", "21000");
        }

        updateCount = result.getUpdateCount();
        return updateCount;
    }

    @Override
    public boolean execute(String sql) throws SQLException {
        checkClosed();
        clearResults();

        SBQueryResult result = connection.getProtocol().execute(sql, maxRows, queryTimeout * 1000);

        if (result.getColumns() != null && !result.getColumns().isEmpty()) {
            currentResultSet = new SBResultSet(this, result.getColumns(), result.getRows());
            updateCount = -1;
            return true;
        } else {
            updateCount = result.getUpdateCount();
            return false;
        }
    }

    @Override
    public boolean execute(String sql, int autoGeneratedKeys) throws SQLException {
        if (autoGeneratedKeys == Statement.RETURN_GENERATED_KEYS) {
            // Append RETURNING clause if not present
            if (!sql.toUpperCase().contains("RETURNING")) {
                sql = sql + " RETURNING *";
            }
        }
        return execute(sql);
    }

    @Override
    public boolean execute(String sql, int[] columnIndexes) throws SQLException {
        // For generated keys by column index
        return execute(sql, Statement.RETURN_GENERATED_KEYS);
    }

    @Override
    public boolean execute(String sql, String[] columnNames) throws SQLException {
        if (columnNames != null && columnNames.length > 0) {
            StringBuilder returning = new StringBuilder(" RETURNING ");
            for (int i = 0; i < columnNames.length; i++) {
                if (i > 0) returning.append(", ");
                returning.append(columnNames[i]);
            }
            sql = sql + returning.toString();
        }
        return execute(sql);
    }

    @Override
    public int executeUpdate(String sql, int autoGeneratedKeys) throws SQLException {
        execute(sql, autoGeneratedKeys);
        return (int) updateCount;
    }

    @Override
    public int executeUpdate(String sql, int[] columnIndexes) throws SQLException {
        execute(sql, columnIndexes);
        return (int) updateCount;
    }

    @Override
    public int executeUpdate(String sql, String[] columnNames) throws SQLException {
        execute(sql, columnNames);
        return (int) updateCount;
    }

    @Override
    public void close() throws SQLException {
        if (closed.compareAndSet(false, true)) {
            if (currentResultSet != null) {
                currentResultSet.close();
                currentResultSet = null;
            }
            batchStatements.clear();
        }
    }

    @Override
    public int getMaxFieldSize() throws SQLException {
        checkClosed();
        return maxFieldSize;
    }

    @Override
    public void setMaxFieldSize(int max) throws SQLException {
        checkClosed();
        if (max < 0) {
            throw new SQLException("Max field size must be >= 0", "HY024");
        }
        this.maxFieldSize = max;
    }

    @Override
    public int getMaxRows() throws SQLException {
        checkClosed();
        return maxRows;
    }

    @Override
    public void setMaxRows(int max) throws SQLException {
        checkClosed();
        if (max < 0) {
            throw new SQLException("Max rows must be >= 0", "HY024");
        }
        this.maxRows = max;
        this.largeMaxRows = max;
    }

    @Override
    public long getLargeMaxRows() throws SQLException {
        checkClosed();
        return largeMaxRows;
    }

    @Override
    public void setLargeMaxRows(long max) throws SQLException {
        checkClosed();
        if (max < 0) {
            throw new SQLException("Max rows must be >= 0", "HY024");
        }
        this.largeMaxRows = max;
        this.maxRows = max > Integer.MAX_VALUE ? Integer.MAX_VALUE : (int) max;
    }

    @Override
    public void setEscapeProcessing(boolean enable) throws SQLException {
        checkClosed();
        // JDBC escape processing is always enabled
    }

    @Override
    public int getQueryTimeout() throws SQLException {
        checkClosed();
        return queryTimeout;
    }

    @Override
    public void setQueryTimeout(int seconds) throws SQLException {
        checkClosed();
        if (seconds < 0) {
            throw new SQLException("Query timeout must be >= 0", "HY024");
        }
        this.queryTimeout = seconds;
    }

    @Override
    public void cancel() throws SQLException {
        checkClosed();
        connection.cancelQuery();
    }

    @Override
    public SQLWarning getWarnings() throws SQLException {
        checkClosed();
        return warnings;
    }

    @Override
    public void clearWarnings() throws SQLException {
        checkClosed();
        warnings = null;
    }

    @Override
    public void setCursorName(String name) throws SQLException {
        checkClosed();
        this.cursorName = name;
    }

    @Override
    public ResultSet getResultSet() throws SQLException {
        checkClosed();
        return currentResultSet;
    }

    @Override
    public int getUpdateCount() throws SQLException {
        checkClosed();
        return updateCount > Integer.MAX_VALUE ? Integer.MAX_VALUE : (int) updateCount;
    }

    @Override
    public long getLargeUpdateCount() throws SQLException {
        checkClosed();
        return updateCount;
    }

    @Override
    public boolean getMoreResults() throws SQLException {
        return getMoreResults(Statement.CLOSE_CURRENT_RESULT);
    }

    @Override
    public boolean getMoreResults(int current) throws SQLException {
        checkClosed();

        if (current == Statement.CLOSE_CURRENT_RESULT ||
            current == Statement.CLOSE_ALL_RESULTS) {
            if (currentResultSet != null) {
                currentResultSet.close();
                currentResultSet = null;
            }
        }

        // ScratchBird doesn't support multiple result sets from single query yet
        updateCount = -1;
        return false;
    }

    @Override
    public void setFetchDirection(int direction) throws SQLException {
        checkClosed();
        if (direction != ResultSet.FETCH_FORWARD &&
            direction != ResultSet.FETCH_REVERSE &&
            direction != ResultSet.FETCH_UNKNOWN) {
            throw new SQLException("Invalid fetch direction: " + direction, "HY024");
        }
        this.fetchDirection = direction;
    }

    @Override
    public int getFetchDirection() throws SQLException {
        checkClosed();
        return fetchDirection;
    }

    @Override
    public void setFetchSize(int rows) throws SQLException {
        checkClosed();
        if (rows < 0) {
            throw new SQLException("Fetch size must be >= 0", "HY024");
        }
        this.fetchSize = rows;
    }

    @Override
    public int getFetchSize() throws SQLException {
        checkClosed();
        return fetchSize;
    }

    @Override
    public int getResultSetConcurrency() throws SQLException {
        checkClosed();
        return resultSetConcurrency;
    }

    @Override
    public int getResultSetType() throws SQLException {
        checkClosed();
        return resultSetType;
    }

    @Override
    public void addBatch(String sql) throws SQLException {
        checkClosed();
        batchStatements.add(sql);
    }

    @Override
    public void clearBatch() throws SQLException {
        checkClosed();
        batchStatements.clear();
    }

    @Override
    public int[] executeBatch() throws SQLException {
        checkClosed();

        int[] results = new int[batchStatements.size()];
        SQLException firstException = null;

        for (int i = 0; i < batchStatements.size(); i++) {
            try {
                int count = executeUpdate(batchStatements.get(i));
                results[i] = count;
            } catch (SQLException e) {
                results[i] = Statement.EXECUTE_FAILED;
                if (firstException == null) {
                    firstException = e;
                }
            }
        }

        batchStatements.clear();

        if (firstException != null) {
            throw new BatchUpdateException(firstException.getMessage(),
                firstException.getSQLState(), firstException.getErrorCode(),
                results, firstException);
        }

        return results;
    }

    @Override
    public long[] executeLargeBatch() throws SQLException {
        checkClosed();

        long[] results = new long[batchStatements.size()];
        SQLException firstException = null;

        for (int i = 0; i < batchStatements.size(); i++) {
            try {
                long count = executeLargeUpdate(batchStatements.get(i));
                results[i] = count;
            } catch (SQLException e) {
                results[i] = Statement.EXECUTE_FAILED;
                if (firstException == null) {
                    firstException = e;
                }
            }
        }

        batchStatements.clear();

        if (firstException != null) {
            int[] intResults = new int[results.length];
            for (int i = 0; i < results.length; i++) {
                intResults[i] = results[i] > Integer.MAX_VALUE ?
                    Integer.MAX_VALUE : (int) results[i];
            }
            throw new BatchUpdateException(firstException.getMessage(),
                firstException.getSQLState(), firstException.getErrorCode(),
                intResults, firstException);
        }

        return results;
    }

    @Override
    public Connection getConnection() throws SQLException {
        checkClosed();
        return connection;
    }

    @Override
    public ResultSet getGeneratedKeys() throws SQLException {
        checkClosed();
        if (generatedKeys == null) {
            // Return empty result set
            return new SBResultSet(this, Collections.emptyList(), Collections.emptyList());
        }
        return generatedKeys;
    }

    @Override
    public int getResultSetHoldability() throws SQLException {
        checkClosed();
        return resultSetHoldability;
    }

    @Override
    public boolean isClosed() throws SQLException {
        return closed.get();
    }

    @Override
    public void setPoolable(boolean poolable) throws SQLException {
        checkClosed();
        this.poolable = poolable;
    }

    @Override
    public boolean isPoolable() throws SQLException {
        checkClosed();
        return poolable;
    }

    @Override
    public void closeOnCompletion() throws SQLException {
        checkClosed();
        this.closeOnCompletion = true;
    }

    @Override
    public boolean isCloseOnCompletion() throws SQLException {
        checkClosed();
        return closeOnCompletion;
    }

    @Override
    public <T> T unwrap(Class<T> iface) throws SQLException {
        if (iface.isAssignableFrom(getClass())) {
            return iface.cast(this);
        }
        throw new SQLException("Cannot unwrap to " + iface.getName(), "0A000");
    }

    @Override
    public boolean isWrapperFor(Class<?> iface) throws SQLException {
        return iface.isAssignableFrom(getClass());
    }

    // ==================== Protected Methods ====================

    protected void checkClosed() throws SQLException {
        if (closed.get()) {
            throw new SQLException("Statement is closed", "HY010");
        }
        if (connection.isClosed()) {
            throw new SQLException("Connection is closed", "08003");
        }
    }

    protected void clearResults() {
        if (currentResultSet != null) {
            try {
                currentResultSet.close();
            } catch (SQLException e) {
                // Ignore
            }
            currentResultSet = null;
        }
        updateCount = -1;
        moreResults = false;
        generatedKeys = null;
    }

    protected void addWarning(SQLWarning warning) {
        if (warnings == null) {
            warnings = warning;
        } else {
            warnings.setNextWarning(warning);
        }
    }

    /**
     * Checks for close on completion.
     */
    void checkCloseOnCompletion() throws SQLException {
        if (closeOnCompletion && currentResultSet != null && currentResultSet.isClosed()) {
            close();
        }
    }
}
